<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>traducteur anglais français</title>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans">
    <link rel="stylesheet" href="index.css">
</head>
<body>
    <header>
<h1>Traduction anglais français</h1>

    </header>
  <main>
            <form action="index.php" method="POST">
                <ul>
                    <li>
                        <label for="word">Mot :</label>
                        <input type="text" id="word" name="word">
                    <div></div></li>
                    <li>
                        <label for="direction">Sens de traduction :</label>
                        <select id="direction" name="direction">
                            <option value="toEnglish">Français vers Anglais</option>
                            <option value="toFrench">Anglais vers Français</option>
                        </select>
                    </li>
                    <li>
                        <input type="submit" value="Traduire">
                    </li>
                </ul>
            </form>

            </main>
</body>
</html>


