<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<form  action="register.php" method="post">

	<label>mail</label>
    <input type="text" name="mail" >

    <label>password</label>
    <input type="text" name="password" >

    <label>nom</label>
    <input type="text" name="nom" >

    <label> Prenom</label>
    <input type="text" name="prenom" >


    <label> Pseudo</label>
    <input type="text" name="pseudo" >


    <button type="submit">Enregistrer</button>


</form>
</body>
</html>